"""Render the native supervision surface. Presentation only."""
from __future__ import annotations
from pathlib import Path
from .schema import Habitat, Job, Signal, Action
from html import escape

def render_dashboard(habitat: Habitat, jobs: list[Job], signals: list[Signal], actions: list[Action], title="Habitat") -> str:
    unresolved = [s for s in signals if s.resolved_at is None and s.severity in ("critical", "warning")]
    unresolved.sort(key=lambda s: (0 if s.severity == "critical" else 1, s.detected_at), reverse=False)
    enabled = sum(j.enabled for j in jobs); ok = sum(j.last_status == "ok" for j in jobs); failed = sum(j.last_status == "failed" for j in jobs)
    attention = "".join(f'<div class="signal"><span class="badge {escape(s.severity)}">{escape(s.severity.upper())}</span><strong>{escape(s.code)}</strong> — {escape(s.message)}</div>' for s in unresolved) or '<div class="ok">All clear. Nothing needs attention.</div>'
    rows = "".join(f'<tr><td>{escape(j.name)}</td><td>{"yes" if j.enabled else "no"}</td><td>{escape(j.last_status or "—")}</td><td>{j.failure_streak}</td><td>{escape(j.last_error or "—")}</td></tr>' for j in jobs) or '<tr><td colspan="5">No jobs</td></tr>'
    acts = "".join(f'<tr><td>{escape(a.timestamp.strftime("%Y-%m-%d %H:%M"))}</td><td>{escape(a.actor)}</td><td>{escape(a.action)}</td><td>{escape(a.status)}</td></tr>' for a in actions[:20]) or '<tr><td colspan="4">No recent actions</td></tr>'
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} — Supervision</title><style>:root{{--bg:#0f1115;--panel:#171a20;--text:#e6e8ee;--muted:#8f98a8;--ok:#3dd68c;--warn:#f5a524;--crit:#f31260;--border:#292e38}}*{{box-sizing:border-box}}body{{margin:0;padding:32px;font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--text);line-height:1.5}}main{{max-width:1100px;margin:auto}}h1{{margin:0 0 4px;font-size:24px}}.sub{{color:var(--muted);font-size:13px;margin-bottom:24px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:16px}}.kpi,.panel{{background:var(--panel);border:1px solid var(--border);border-radius:10px}}.kpi{{padding:16px}}.v{{font-size:26px;font-weight:650}}.l,h2{{color:var(--muted);font-size:12px}}.l{{margin-top:3px}}.panel{{padding:18px;margin-bottom:16px}}h2{{margin:0 0 12px;text-transform:uppercase;letter-spacing:.05em}}.attn{{border-color:var(--crit)}}.calm{{border-color:var(--ok)}}.ok{{color:var(--ok)}}.signal{{margin:8px 0}}.badge{{display:inline-block;font-size:10px;font-weight:800;padding:2px 6px;border-radius:4px;margin-right:6px}}.critical{{background:var(--crit);color:#fff}}.warning{{background:var(--warn);color:#111}}table{{width:100%;border-collapse:collapse;font-size:13px}}th,td{{padding:8px;text-align:left;border-bottom:1px solid var(--border)}}th{{color:var(--muted);font-weight:500;font-size:11px}}@media(max-width:650px){{body{{padding:18px}}table{{font-size:12px}}}}</style></head><body><main><h1>{escape(title)}</h1><div class="sub">status: <strong>{escape(habitat.status)}</strong> · model: {escape(habitat.model)} · local-first supervision</div><div class="grid"><div class="kpi"><div class="v">{enabled}<small>/{len(jobs)}</small></div><div class="l">Jobs enabled</div></div><div class="kpi"><div class="v">{ok}</div><div class="l">OK runs</div></div><div class="kpi"><div class="v">{failed}</div><div class="l">Failed</div></div><div class="kpi"><div class="v">{len(unresolved)}</div><div class="l">Needs attention</div></div></div><section class="panel {"attn" if unresolved else "calm"}"><h2>Needs attention</h2>{attention}</section><section class="panel"><h2>Jobs & health</h2><table><thead><tr><th>Name</th><th>Enabled</th><th>Last status</th><th>Failure streak</th><th>Last error</th></tr></thead><tbody>{rows}</tbody></table></section><section class="panel"><h2>Recent actions</h2><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Status</th></tr></thead><tbody>{acts}</tbody></table></section></main></body></html>'''

def write_dashboard(html: str, path: str | Path) -> Path:
    p = Path(path); p.write_text(html, encoding="utf-8"); return p
